MvcPrimeraPracticaNetCoreAlberto/Models/ErrorViewModel.cs
namespace MvcPrimeraPracticaNetCoreAlberto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcPrimeraPracticaNetCoreAlberto/Models/ImagenesZapas.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcPrimeraPracticaNetCoreAlberto.Models
{
    [Table("IMAGENESZAPASPRACTICA")]
    public class ImagenesZapas
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }

        [Column("IDPRODCUTO")]
        public int IdProducto { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

MvcPrimeraPracticaNetCoreAlberto/Models/PaginacionZapatillas.cs
namespace MvcPrimeraPracticaNetCoreAlberto.Models
{
    public class PaginacionZapatillas
    {
        public Zapatillas Zapatillas { get; set; }
        public int numeroRegistros { get; set; }
        public ImagenesZapas ImagenZapas {  get; set; } 

    }
}

MvcPrimeraPracticaNetCoreAlberto/Models/Zapatillas.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcPrimeraPracticaNetCoreAlberto.Models
{
    [Table("ZAPASPRACTICA")]
    public class Zapatillas
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }

        [Column("PRECIO")]
        public int Precio { get; set; }

    }
}

MvcPrimeraPracticaNetCoreAlberto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPrimeraPracticaNetCoreAlberto.Models;
using System.Diagnostics;

namespace MvcPrimeraPracticaNetCoreAlberto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPrimeraPracticaNetCoreAlberto/Controllers/ZapatillasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPrimeraPracticaNetCoreAlberto.Models;
using MvcPrimeraPracticaNetCoreAlberto.Respository;
using System.Runtime.InteropServices;

namespace MvcPrimeraPracticaNetCoreAlberto.Controllers
{
    public class ZapatillasController : Controller
    {
        private RepositoryZapatillas repo;

        public ZapatillasController(RepositoryZapatillas repo)

        {

            this.repo = repo;

        }

        public async Task<IActionResult> Index()
        {
            List<Zapatillas> zapatillas = await this.repo.GetZapatillasAsync();

            return View(zapatillas);
        }

        public async Task<IActionResult> Details(int idZapatilla)
        {
            PaginacionZapatillas pagZapas = await this.repo.GetPaginacionZapatillasAsync(1, idZapatilla);
            return View(pagZapas);
        }

        public async Task<IActionResult> PaginacionZapatillas(int? posicion, int idZapatilla)
        {
            if(posicion == null)
            {
                posicion = 1;
            }
            PaginacionZapatillas pagZapas = await this.repo.GetPaginacionZapatillasAsync(posicion.Value, idZapatilla);
            int numeroRegistros = pagZapas.numeroRegistros;
            int siguiente = posicion.Value + 1;
            if(siguiente > numeroRegistros)
                siguiente = numeroRegistros;
            int anterior = posicion.Value - 1;
            if (anterior < 1)
                anterior = 1;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["ULTIMO"] = pagZapas.numeroRegistros;
            ViewData["ZAPATILLA"] = pagZapas.Zapatillas;
            ViewData["POSICION"] = posicion;
            return PartialView("PaginacionZapatillas", pagZapas.ImagenZapas);
        }

        public async Task<IActionResult> InsertarImagen()
        {
            List<Zapatillas> zapatillas = await this.repo.GetZapatillasAsync();
            return View(zapatillas);
        }

        [HttpPost]
        public async Task<IActionResult> InsertarImagen(List<string> imagenes, int idZapatailla)
        {
            await this.repo.InsertarImagen(imagenes, idZapatailla);
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcPrimeraPracticaNetCoreAlberto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPrimeraPracticaNetCoreAlberto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcPrimeraPracticaNetCoreAlberto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcPrimeraPracticaNetCoreAlberto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcPrimeraPracticaNetCoreAlberto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="Index">Zapatillas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="InsertarImagen">Zapatillas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcPrimeraPracticaNetCoreAlberto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcPrimeraPracticaNetCoreAlberto/Views/Zapatillas/Details.cshtml
@{
    Zapatillas zapatillas = ViewData["ZAPATILLAS"] as Zapatillas;
}

<a asp-controller="Zapatillas" asp-action="Index">Volver</a>
<div class="card">
    <div class="card-body">
        <h4>@zapatillas.Nombre</h4>
        <h4>@zapatillas.Precio: @zapatillas.Precio</h4>
        <h4>@zapatillas.@zapatillas.Descripcion</h4>
    </div>
</div>

@section Scripts {
    <script>
        function loadZapatillasPaginacion(posicion) {
            $(function () {
                $("#contenidoImagen").load("/PaginacionZapatillas?posicion="
                    + posicion + "&idZapatilla=" + @zapatillas.IdProducto);
            });
        }

        loadZapatillasPaginacion(1);
    </script>
}

MvcPrimeraPracticaNetCoreAlberto/Views/Zapatillas/Index.cshtml
@model List<Zapatillas>
<h1>Zapatillas</h1>
<ul class="list-group">
    @foreach (Zapatillas zapa in Model)
    {
        <li class="list-item-group">
            <a asp-controller="Zapatillas" asp-action="Details" asp-route-idzapatilla="@zapa.IdProducto">
                Detalles de @zapa.Nombre
            </a>
        </li>
    }
</ul>

MvcPrimeraPracticaNetCoreAlberto/Views/Zapatillas/InsertarImagen.cshtml
@model MvcPrimeraPracticaNetCoreAlberto.Models.Zapatillas

@{
    ViewData["Title"] = "InsertarImagen";
}

<h1>InsertarImagen</h1>

<h4>Zapatillas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="InsertarImagen">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdProducto" class="control-label"></label>
                <input asp-for="IdProducto" class="form-control" />
                <span asp-validation-for="IdProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcPrimeraPracticaNetCoreAlberto/Views/Zapatillas/PaginacionZapatillas.cshtml
@model ImagenesZapas

<div class="card">
    <div class="card-body">
        <h5">
            Imagen @ViewData["POSICION"] de @ViewData["ULTIMO"]
        </h5>
        <button onclick="loadZapatillasPaginacion(1)">
            Primero
        </button>
        <button onclick="loadZapatillasPaginacion(@ViewData["ANTERIOR"])">
            Anterior
        </button>
            <button onclick="loadZapatillasPaginacion(@ViewData["SIGUIENTE"])">
                Siguiente
            </button>
            <button onclick="loadZapatillasPaginacion(@ViewData["ULTIMO"])">
                Ultimo
            </button>
            <div>

                <img src="@Model.Imagen" style="width: 100px" height="100px"/>
            </div>
    </div>
</div>